### ISSUE TITLE
使用用户名和密码登录问题

### ISSUE THREAD

**Issue by ghost** [Kylsky/pandora-helper-with-linux-do-oauth#2]
因为没有linux-do账号，所以无法设置oauth，但是看到又设置管理员用户名，已设置管理员用户名，然后登录的时候默认密码是多少呢？谢谢大佬解惑。

**Comment by Kylsky** [comment]
默认密码是123456

**Comment by Kylsky** [comment]
我更新一下说明

**Comment by ztj7728** [comment]
<img width="413" alt="1" src="https://github.com/user-attachments/assets/6a88eefb-0c50-431d-b611-a4192d96efe0" />
大佬，这样的提示是咋回事，密码是123456呀

**Comment by ztj7728** [comment]
已解决，原因是自定义域名没有加https://
