### ISSUE TITLE
申请时的回调地址如何填写

### ISSUE THREAD

**Issue by L1bws** [Kylsky/pandora-helper-with-linux-do-oauth#3]
![image](https://github.com/user-attachments/assets/427d91b3-4b93-47c8-94ac-d8e93cc77329)
就是这个参数，我用默认的 http://localhost:8181/oauth2/callback 只会显示一串登录信息的json，没法登录

**Comment by Kylsky** [comment]
<img width="719" alt="image" src="https://github.com/user-attachments/assets/0b22f067-2ddd-4e75-ae47-6f009c0bac74">

**Comment by L1bws** [comment]
OK
